### ISSUE TITLE
Fails when ESLint config isn't available

### ISSUE THREAD

**Issue by aarondancer** [kentcdodds/prettier-eslint-atom#7]
[Enter steps to reproduce below:]

1. Run `prettier-eslint-atom` on a file in a project that doesn't have an ESLint config. 

**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.2
**Thrown From**: [prettier-eslint-atom](https://github.com/kentcdodds/prettier-eslint-atom) package, v1.0.6

### Stack Trace

Uncaught TypeError: Cannot read property 'split' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:872

TypeError: Cannot read property 'split' of undefined
  at Function.module.exports.Range.fromText (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/range.js:47:19)
  at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:608:24)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:596:26
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:867:18)
  at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:594:21)
  at TextBuffer.module.exports.TextBuffer.setText (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:534:19)
  at TextEditor.module.exports.TextEditor.setText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1085:26)
  at Object.format (/Users/aarondancer/.atom/packages/prettier-eslint-atom/lib/prettier-eslint-atom.js:64:14)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:210:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:587:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:382:22)
  at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59)

```

### Commands

```
     -0:02.7.0 command-palette:toggle (input.hidden-input)
     -0:00.2.0 core:confirm (input.hidden-input)
     -0:00.2.0 prettier-eslint:format (input.hidden-input)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".hgrc",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "language-javascript",
      "language-javascript-jsx",
      "react",
      "tree-view",
      "linter-write-good",
      "nuclide-format-js",
      "prettier-atom"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "one-dark-ui",
      "gruvbox-plus-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
apex-syntax, v0.1.0 (inactive)
apex-ui, v0.2.1 (inactive)
atom-beautify, v0.29.16 (inactive)
atom-material-ui, v1.3.9 (inactive)
autocomplete-modules, v1.6.7 (active)
dark-flat-ui, v1.2.4 (inactive)
docblockr, v0.9.1 (active)
emmet, v2.4.3 (active)
file-icons, v2.0.10 (active)
gruvbox, v1.0.5 (inactive)
gruvbox-plus-syntax, v1.3.1 (active)
gruvbox-syntax, v2.4.1 (inactive)
haskell-grammar, v0.4.0 (active)
highlight-selected, v0.12.0 (active)
hybrid-next-syntax, v0.9.1 (inactive)
js-hyperclick, v1.10.1 (active)
language-babel, v2.49.4 (active)
language-graphql, v0.8.0 (active)
language-ini, v1.17.0 (active)
language-javascript-jsx, v0.3.7 (inactive)
language-lua, v0.9.11 (active)
language-ocaml, v1.1.2 (active)
language-swift, v0.5.0 (active)
language-thrift, v1.0.2 (active)
linter, v1.11.21 (active)
linter-eslint, v8.0.0 (active)
linter-write-good, v0.8.0 (inactive)
mac-classic, v0.4.0 (inactive)
merge-conflicts, v1.4.4 (active)
min-ui, v0.0.1 (inactive)
native-ui, v0.20.3 (inactive)
next-dark-ui, v0.4.0 (inactive)
nord-atom-ui, v0.9.0 (inactive)
nucleus-dark-ui, v0.10.22 (inactive)
nuclide, v0.200.0 (active)
nuclide-format-js, v0.0.36 (inactive)
oceanic-next, v1.0.0 (inactive)
pigments, v0.38.0 (active)
prettier-atom, v0.0.10 (inactive)
prettier-eslint-atom, v1.0.6 (active)
react, v0.16.2 (inactive)
react-snippets, v0.5.0 (active)
set-syntax, v0.3.2 (active)
seti-ui, v1.4.0 (inactive)
slim-dark-ui, v0.12.0 (inactive)
sort-lines, v0.14.0 (inactive)
tool-bar, v1.0.1 (active)
unity-dark-ui, v2.0.9 (inactive)
unity-ui, v2.1.8 (inactive)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (active)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (inactive)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (inactive)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by kentcdodds** [comment]
Thanks for reporting this. Would you be interested in contributing a fix?

**Comment by aarondancer** [comment]
I'll give it a shot 👍

**Comment by kentcdodds** [comment]
This package has been deprecated. Please see the README for instructions on moving to the new plugin.
